version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: alx_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234           # Change this to something stronger in prod
      MYSQL_DATABASE: alx_db              # Optional: creates a default database
      MYSQL_USER: liam                # Optional: creates a new user
      MYSQL_PASSWORD: 1234            # Optional: sets that user's password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

