apiVersion: apps/v1
kind: Deployment
metadata:
  name: messaging-app-blue
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
        maxUnavailable: 1
        maxSurge: 1
  selector:
    matchLabels:
      app: messaging-app
      env: blue
  template:
    metadata:
      labels:
        app: messaging-app
        env: blue
    spec:
      containers:
      - name: messaging-app
        image: messaging-app:v2.0
        imagePullPolicy: Never
        ports:
        - containerPort: 8080