apiVersion: apps/v1
kind: Deployment
metadata:
  name: messaging-app-green
spec:
  replicas: 3
  selector:
    matchLabels:
      app: messaging-app
      env: green
  template:
    metadata:
      labels:
        app: messaging-app
        env: green
    spec:
      containers:
      - name: messaging-app
        image: messaging-app:green
        imagePullPolicy: Never
        ports:
        - containerPort: 8080