#!/bin/bash

# Scale to 3 replicas
kubectl scale deployment messaging-app --replicas=3

# Verify
kubectl get pods

# Get the service URL
SERVICE_URL=$(minikube service messaging-app-service --url)

# Test workload
wrk -t4 -c100 -d30s "$SERVICE_URL"

# Monitor resource use
kubectl top pods