pipeline {
    agent any

    environment {
        VENV = "venv"
        IMAGE_NAME = 'Wmugacha/messaging-app'
        TAG = "${new Date().format('yyyyMMddHHmmss')}"
        DOCKER_CREDENTIALS_ID = 'dockerhub-creds'
    }

    stages {
        stage('Clone Repo') {
            steps {
                git branch: 'main', credentialsId: 'github-creds', url: 'https://github.com/Wmugacha/alx-backend-python.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('messaging_app') {
                    sh '''
                        python3 -m venv venv
                        ./venv/bin/python -m ensurepip --upgrade
                        ./venv/bin/python -m pip install --upgrade pip
                        ./venv/bin/python -m pip install -r requirements.txt
                    '''
                }
            }
        }

        stage('Run Tests') {
            steps {
                dir('messaging_app') {
                    sh './venv/bin/pytest --junitxml=../report.xml'
                }
            }
        }

        stage('Publish Report') {
            steps {
                junit 'report.xml'
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('messaging_app') {
                    sh 'docker build -t $IMAGE_NAME:$TAG .'
                }
            }
        }

        stage('Push to Docker Hub') {
            steps {
                withCredentials([usernamePassword(credentialsId: "${DOCKER_CREDENTIALS_ID}", usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    sh '''
                        echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
                        docker push $IMAGE_NAME:$TAG
                        docker logout
                    '''
                }
            }
        }
    }
}
