#!/bin/bash

echo "Starting Minikube Cluster...."
minikube start

echo "Checking Cluster Status..."
kubectl cluster-info

echo "🔍 Checking Minikube status..."
minikube status

echo "📦 Getting node status..."
kubectl get nodes

echo "🧠 Verifying core components..."
kubectl get pods -A
